### ISSUE TITLE
Request for further categorization of Repository

### ISSUE THREAD

**Issue by kots14** [piyush6348/Design-Patterns#2]
We can have the design patterns in the repository categorized under 

- Creational Patterns
- Structural Patterns 
- Behavioral Patterns 

at a directory level.

Although documentation is there in the main README file, if we can put this for navigation through the repository that would be great.

**Comment by piyush6348** [comment]
Sure @kots14 Please go ahead and have a PR.

**Comment by kots14** [comment]
I've raised a PR for this. 
I'm closing this issue now as we can work more over the PR if required.
Thanks :)
